### PR TITLE
:new: Textfield checkfocus

### LINKED ISSUE #1125: autofocus attribute doesn't work
autofocus native HTML5 attribute doesn't work with material-design-lite

### PR DESCRIPTION
**Pull request by Garbee**
Fixes #1125 

No unit test since nothing I tried to test this functionality would work. Looks like the `focus()` method on inputs in a test focusing seems to be an issue. I manually tested by opening a snippet and adding `autofocus` to one, then going to http://localhost:5000/components/textfield/demo.html and seeing if it were focused or not. Works as expected.

### CODE REVIEW

**Comment by surma** [comment]
LGTM

File: src/textfield/textfield.js [hunk 1]
```diff
@@ -169,6 +170,21 @@
...
   /**
+  * Check the focus state and update field accordingly.
+  *
+  * @public
+  */
+  MaterialTextfield.prototype.checkFocus = function() {
+    if (Boolean(this.element_.querySelector(':focus'))) {
+      this.element_.classList.add(this.CssClasses_.IS_FOCUSED);
+    } else {
+      this.element_.classList.remove(this.CssClasses_.IS_DIRTY);
```
Comment (sgomes) [inline src/textfield/textfield.js]: Shouldn't we be removing `IS_FOCUSED` instead of `IS_DIRTY`?

Comment (Garbee) [inline src/textfield/textfield.js]: Good catch, atom autocomplete fail.

**Comment by sgomes** [comment]
Tested in IE10, works there. LGTM, merge at will!
