### PR TITLE
fix accessibility of drawer button and drawer itself

### LINKED ISSUE #1179: several accessibility bugs in layout
MDL version: 1.0.0
Browser: Chrome 
Browser version: 43
Operating system: Ubuntu 
Operating system version: 14.04
URL: 
http://www.getmdl.io/templates/android-dot-com/index.html
http://www.getmdl.io/components/index.html#layout-section

What steps will reproduce the problem:
1. open page
2. press [TAB]
3. navigation should be closed by pressing [ESC]

What is the expected result?
drawer button will be focused. With a press on [Enter] the drawer navigation will be opened.

What happens instead of that?
Another element will be focused. E.g. in the Android template the search input field will be focused. Here seems to be the next glitch. The links in the horizontal navigation will be focused after the search field. So the element order not match witch the tab order. 

My proposal for a solution:
- the .mdl-layout__drawer-button should be a button, not a div
- add missing aria attributes (aria-expanded to the button, aria-hidden to the navigatio. Maybe aria-owns to the button, iam not shure about that)
- drawer navigation items get tabindex of -1, if drawer nav is closed and 0 if drawer nav is open
- the html elements of the navigation elements (links and search input) should be in the right order in the markup and not be positioned by to many css magic (order change with flexbox)
- close navigation on pressing [ESC]

### PR DESCRIPTION
**Pull request by tschiela**
fix #1179

- change drawer button tag from div to button to make it focusable
- focus first link in drawer nav if drawer will be opened for easier keyboard navigation with tab
- close drawer on hitting ESC
- added tests

### CODE REVIEW

File: src/layout/layout.js [hunk 1]
```diff
@@ -74,6 +84,7 @@
     CONTAINER: 'mdl-layout__container',
     HEADER: 'mdl-layout__header',
     DRAWER: 'mdl-layout__drawer',
+    DRAWER_LINKS: 'mdl-layout__drawer a',
```
Comment (Garbee) [inline src/layout/layout.js]: This object is specifically to hold CSS classes used in the system. Not general selectors for any given query statement. Instead write your query selector ( line 189 ) as `document.querySelector('.' + this.CssClasses_.DRAWER + ' a')`. This will re-use the existing class as it should, while not expanding the scope for what this property holds.

File: src/layout/layout.js [hunk 2]
```diff
@@ -287,7 +326,8 @@
         var drawerButton = this.element_.querySelector('.' +
           this.CssClasses_.DRAWER_BTN);
         if (!drawerButton) {
-          drawerButton = document.createElement('div');
+          drawerButton = document.createElement('button');
```
Comment (Garbee) [inline src/layout/layout.js]: Sadly, changing this from a `div` now could be a BC Break. Since, developers could be expecting `div.mdl-layout__drawer-button` to exist for selectors.

File: test/unit/layout.js [hunk 3]
```diff
@@ -97,4 +97,66 @@ describe('MaterialLayout', function () {
...
+      var ev = document.createEvent('KeyboardEvent');
+      ev.initEvent('keydown', true, true, null, false, false, false, false, 27, 0);
+      drawer.dispatchEvent(ev);
+
+      window.setTimeout(function () {
+        expect($(drawer)).to.not.have.class('is-visible');
+        expect($(drawer)).to.have.attr('aria-hidden', 'true');
+        expect($(drawerBtn)).to.have.attr('aria-expanded', 'false');
+        // need chai-jquery 2.0.1 for .have.focus();
+        //expect($(drawerBtn)).have.focus();
```
Comment (Garbee) [inline test/unit/layout.js]: Why is this in the test? If you want to check focus in the test, then add the dep in package.json and update the PR. Otherwise, remove the comments since they are doing no good being here.

File: test/unit/layout.js [hunk 4]
```diff
@@ -97,4 +97,66 @@ describe('MaterialLayout', function () {
...
+    it('button should have attribute aria-expanded="false"', function () {
+      expect($(drawerBtn)).to.have.attr('aria-expanded', 'false');
+    });
+
+    it('and drawer button should have correct values for attributes aria-hidden and aria-expanded', function (done) {
+      var ev = document.createEvent('MouseEvents');
+      ev.initEvent('click', true, true);
+      drawerBtn.dispatchEvent(ev);
+
+      window.setTimeout(function () {
```
Comment (Garbee) [inline test/unit/layout.js]: This seems odd to me. Why do expectations within a timeout?

**Comment by tschiela** [comment]
@Garbee thanks for your suggestions. Using a DIV as button its possible in a view of accessibility, but makes implementation of keyboard interactions more complicated not to mention sematic HTML. For a futute release that should be changed in my opinion.

chai-jquery 2.0.1 is not on npm at the moment. I dont know if you want to point to a specific commit in the package.json or just wait until its on npm. So if you update chai-jquery i could write more advanced test.

**Comment by Garbee** [comment]
With V2 for layout we are leaving pretty much all of the elements used up  to the developer. So the div/button thing won't be an issue. As far as a11y is concerned, we should be able to make the div act just like a button somehow, it may take a few attributes but as far as I know should be possible.

if it isn't in NPM, then just drop the test comments, as you have done. We can deal with upgrading once it is in a stable state on NPM.

I'll be able to re-review the  PR tomorrow afternoon or so. Thanks for the quick updates!

**Comment by tschiela** [comment]
In the current state of the PR the toggleDrawer_() is private. In my opinion it sould be public to call it from from custom scripts. What did you think?

**Comment by Garbee** [comment]
We are discussing making it public in another thread. Also out of scope for
this PR.

File: templates/android-dot-com/index.html [hunk 5]
```diff
@@ -86,7 +86,7 @@
         </div>
       </div>
 
-      <div class="android-drawer mdl-layout__drawer">
+      <div class="android-drawer mdl-layout__drawer" aria-hidden="true">
```
Comment (Garbee) [inline templates/android-dot-com/index.html]: Does this attribute need to be set by default for this to work properly on load? I'd prefer it if we set this automatically on initialization for existing integrations to have no changes to benefit from the  improvements.

**Comment by Garbee** [comment]
One final question before merging in. Other than that, PR LGTM.

File: templates/android-dot-com/index.html (hunk 5 above)
Comment (tschiela) [inline templates/android-dot-com/index.html]: The most screen readers do not need valid markup on load. The attribut can be added at runtime. I personally prefer valid markup on load, but thats your decision.

Comment (Garbee) [inline templates/android-dot-com/index.html]: So, in this case let's go ahead and move this into JS during init so it works  the same for  *all* existing sites. Free a11y upgrade without any markup changes in templates is a big win.

**Comment by tschiela** [comment]
```[fatal] Error parsing the .drone.yml```

my commit dont seem to be the problem of that error

**Comment by Garbee** [comment]
We are working on switching testing services at the moment (from Drone to Travis.)

I'll pull this down locally to run tests after breakfast. That way we know without needing to wait on the test service move and can merge it in faster.

It all LGTM just looking over the code changes. The only thing left (assuming my local tests pass fine) is for the commits to get squashed into one. So if you could please go ahead and do that so everything is ready ASAP.

Thanks for the amazing work. Every bit with a11y helps and this PR is wonderfully useful.

**Comment by Garbee** [comment]
Tests are all passing. LGTM.

Assigning to @addyosmani for final review and merge.

**Comment by surma** [comment]
@tschiela You mind rebasing against master?

**Comment by Garbee** [comment]
Attempting a manual merge and conflict resolution...

**Comment by Garbee** [comment]
And manually merged in. Thanks for the patch @tschiela! Awesome work.
